name: Run Application Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install backend dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Start backend server
      run: |
        cd backend
        uvicorn main:app --reload

    - name: Start frontend client
      run: |
        cd frontend
        npm run dev