name: Run Application Tests

on:
  push:
    branches: [ feature/63-initialize-number-of-boards ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      backend:
        image: tiangolo/uvicorn-gunicorn:python3.11
        ports:
          - 8000:8000
        options: >-
          --mount type=bind,source=${{ github.workspace }}/backend,target=/app
        env:
          MODULE_NAME: main
          VARIABLE_NAME: app
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install backend dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Wait for backend to be ready
        run: |
          npx wait-on http://localhost:8000/health

      - name: Run backend tests
        run: |
          cd backend
          pytest

      - name: Run frontend tests
        run: |
          cd frontend
          npm test
